### ISSUE TITLE
Method definition for 'setBlurTintColor:' not found

### ISSUE THREAD

**Issue by robmontesinos** [MatthewYork/MYBlurIntroductionView#13]
Great library! I'm getting the above warning message on the Demo. Any way of resolving this issue with an example of how to apply the blurTintColor properly? Thank you.

**Comment by davidolesch** [comment]
The problem is that [MYBlurIntroductionView](https://github.com/MatthewYork/MYBlurIntroductionView/blob/master/MYBlurIntroductionView/MYBlurIntroductionView.h) declares but does not implement

``` objc
-(void)setBlurTintColor:(UIColor *)blurTintColor;
```

Instead, this method is implemented in [AMBlurView](https://github.com/MatthewYork/MYBlurIntroductionView/blob/master/MYBlurIntroductionView/AMBlurView.m)

**Comment by robmontesinos** [comment]
OK thanks David - I guess I could just comment it out to get rid of the warning

**Comment by MatthewYork** [comment]
FIXED.

I had accidentally misnamed this method. I meant for it to be the setBackgroundColor: method, but must have gotten turned around somewhere along the way. 

Much thanks for catching this.

Regards,

-Matt
