### ISSUE TITLE
MyBlurIntroductionView Rotation

### ISSUE THREAD

**Issue by akanass** [MatthewYork/MYBlurIntroductionView#9]
Hello,

Thanks a lot for your great work.

I've a problem with your plugin when I rotate my phone.
I initialize the view with the controller frame and add it with "addSubView" method but when I pass from Portrait to Landscape, the IntroductionView size doesn't update.

How I can do that?

Thanks in advance,

Best regards.

P.S: Some methods are deprecated in iOS7.

**Comment by MatthewYork** [comment]
Thanks for using MYIntroductionView!

Landscape orientation us not currently supported because, to really do it right, the rendering of stock panels would need to be completely different. In the interim, I will try to make custom panels work landscape. I will let you know when it's ready, or you can do it. Basically, we just need to change the ContentMode.

**Comment by paoloandrea** [comment]
Hi Matthew. Great Work.
Please repair the rotation on iPad and iPhone.
THZ

**Comment by vincentjames501** [comment]
+1

**Comment by DrAma999** [comment]
+1

**Comment by tscc01** [comment]
+1!
thx

**Comment by anka** [comment]
+1

**Comment by KevinHM** [comment]
+1

**Comment by DanH-SyncInteractive** [comment]
+1
